services:
  app:
    build: .
    container_name: tune_tracker_api
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://tune-tracker-db.carvvf7xw1zj.us-east-1.rds.amazonaws.com/tune-tracker-db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=Keyin2025
    ports:
      - "8080:8080"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5