services:
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    container_name: tune_tracker_db
    environment:
      MYSQL_ROOT_PASSWORD: Keyin2025
      MYSQL_DATABASE: tune_tracker
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pKeyin2025"]
      interval: 5s
      timeout: 10s
      retries: 5

  app:
    image: eclipse-temurin:17-jre
    container_name: tune_tracker_api
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/tune_tracker?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    ports:
      - "8080:8080"
    volumes:
      - ./target/Tune-Tracker-API-1.0-SNAPSHOT.jar:/app.jar
    depends_on:
      - mysql
    command: ["java", "-jar", "/app.jar"]

volumes:
  mysql_data: